version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/luxestarspower
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl
    depends_on:
      - php
    networks:
      - luxestarspower

  php:
    image: php:8.2-fpm
    volumes:
      - ./:/var/www/luxestarspower
    environment:
      - DB_HOST=db
      - DB_NAME=luxestarspower
      - DB_USER=luxeuser
      - DB_PASS=secure_password
    networks:
      - luxestarspower

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=luxestarspower
      - MYSQL_USER=luxeuser
      - MYSQL_PASSWORD=secure_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - luxestarspower

  redis:
    image: redis:alpine
    networks:
      - luxestarspower

networks:
  luxestarspower:
    driver: bridge

volumes:
  db_data:
